Update README.md
Vintage-web-production/yii2-search pull request #3
Opened 2018-03-16 15:14 UTC by developer-av

typo in readme

2018-03-17 16:16 UTC, greeflas requested changes
@developer-av Hi! Thank you for your contributing! Can you also fix this typo in doc files?

https://github.com/Vintage-web-production/yii2-search/blob/master/docs/guide-ru/basic-usage.md

https://github.com/Vintage-web-production/yii2-search/blob/master/docs/guide/basic-usage.md

2018-03-18 15:46 UTC, developer-av commented
Hi, You're welcome!

2018-03-18 16:18 UTC, greeflas approved these changes

2018-03-18 16:19 UTC, merged

2018-03-18 16:19 UTC, greeflas commented
@developer-av Merged. Thank you!